### ISSUE TITLE
Implement ZMQ sending

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#12]
Is enabled in XML file for doocs variable config for each variable.
In this file also the variable which contains the macro pulse number is defined.

A first implementation will take the latest macro pulse number. Once the control system adapter has the module to assure data consistency and trigger numbers are passes correctly everywhere, this shall be changed.
A bug ticket shall be created once the feature with the best effort implementation is merged to the master.

**Comment by mhier** [comment]
First implementation is done. The following points are missing:
- Ensure data consistency between data and macro pulse number
- If the data type of the macro pulse number source is not int64_t (and hence we convert via the TypeChangingDecorator), the PV of the macro pulse number source currently cannot be published to the control system, since it is already used by the TypeChangingDecorator. This should be fixed.
- Tests are not complete. Missing are different variants of configuration (macro pulse number source can be specified for each property or for the location) including bad ones (e.g. non-existing macro pulse number source)
- Documentation (should go where?)
- Not directly related to ZMQ: The macro pulse number (and the time stamp from the version number) should also be attached to all data types which support this - not only via ZeroMQ. This should be supported by most DOOCS data types, in particular those with internal buffers (D_spectrum) and histories (D_value).

**Comment by mhier** [comment]
Follow-up tickets have been created, so this ticket can be closed.
