### ISSUE TITLE
ZeroMQ sending: Ensure data consistency between data and macro pulse number

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#14]
Follow up for #12, depends on ChimeraTK/DeviceAccess#25
Use the data consistency group (see ChimeraTK/DeviceAccess#25) to ensure the macro pulse number is always consistent with the data.

If #15 is already done, make sure to ensure data consistency there as well.

**Comment by killenb** [comment]
There is a first implementation on the master. It calls updateDoocsBuffer twice: Once for each macro pulse update and once for the data itself. It does not have a "performance optimisation" that the function pointer dereferencing is only done after checking the consistency group.

Please check if the performance is sufficient. If so please close the ticket, otherwise assign it back to me.

**Comment by mhier** [comment]
It doesn't work at all any more now. I receive the following error message:
```
terminate called after throwing an instance of 'ChimeraTK::logic_error'
  what():  Could not enable ZeroMQ messaging for variable 'M1.A0/VFORW.AMPL'. Code: -2
```

I have tried to launch the llrfctrl server compiled against the latest master versions of ChimeraTK.

**Comment by mhier** [comment]
Performance seems not bad right now. There is still potential for optimisation, I will create a separate ticket for this (#29).
