### ISSUE TITLE
TSAN job is failing

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ControlSystemAdapter-DoocsAdapter#52]
The tread sanitizer is reporting
* 15 data races
* 45 thread leaks
* 1 signal-unsafe call inside of a signal

**Comment by mhier** [comment]
I have found most of them, they are caused by bugs in DOOCS. I will report this to the DOOCS people. Remaining are two reported issues (found both in serverTestSpectrumBuffer and serverTestZeroMQ): one "signal-unsafe call inside of a signal" and one "data race". Both are connected to the termination sequence, which is still not proper.

One key problem is that the RPC thread in DOOCS keeps running while the rest is already shutdown. This leads to a condition variable "cv_ext" being used by the RPC thread after the condition variable has already been destroyed. This causes the data race.

The signal-unsafe call inside of a signal is not understood. Neither in DOOCS nor in our code there are any signal handlers. Instead DOOCS uses sigwait() to deal with signals. The call stack points to a function in glibc's sunrpc implementation, but the stack ends after 3 entries, so we do not know who calls this function. Maybe the sunrpc implementation actually installs a signal handler, but then this would point to a bug in glibc. It could be that this problem prevents the proper termination of the RPC thread.

It is unclear to me how to proceed now. The problems clearly are related to the shutdown mechanism, but this doesn't mean it cannot cause severe problems. A clean shutdown is important so all configuration and cache files are properly closed.

**Comment by mhier** [comment]
I created a suppressions file for the remaining issues, which is used only by a separate Jenkins job. I also created #54 .
